<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.forwardmeasure.testcontainers</groupId>
    <artifactId>forwardmeasure-testcontainers-parent</artifactId>
    <version>${revision}</version>
  </parent>
  <artifactId>forwardmeasure-testcontainers-postgresql</artifactId>
  <name>ForwardMeasure Testcontainers PostgreSQL</name>
  <dependencies>
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>testcontainers-postgresql</artifactId>
    </dependency>
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
    </dependency>
  </dependencies>
</project>
