<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.forwardmeasure.testcontainers</groupId>
    <artifactId>forwardmeasure-testcontainers-parent</artifactId>
    <version>${revision}</version>
  </parent>
  <artifactId>forwardmeasure-testcontainers-bom</artifactId>
  <packaging>pom</packaging>
  <name>ForwardMeasure Testcontainers BOM</name>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>forwardmeasure-testcontainers-keycloak</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>forwardmeasure-testcontainers-minio</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>forwardmeasure-testcontainers-postgresql</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>forwardmeasure-testcontainers-junit-jupiter</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>forwardmeasure-testcontainers-quarkus</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
        <configuration>
          <flattenMode>bom</flattenMode>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
